# Site settings
title: Matt Minhyuk Joo
email: mattjoostudio@gmail.com
url: https://minhyukjoo.github.io
description: "Consultant | Filmmaker | Thinker"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Matt Minhyuk Joo

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/mattjoo/
  - title: github
    url: https://github.com/minhyukjoo
  - title: instagram
    url: https://www.instagram.com/mattjoo.jpg/

# Build settings
markdown: kramdown
permalink: pretty
