# Site settings
title: Matt Minhyuk Joo
email: info@mattjoo.com
url: https://minhyukjoo.github.io
description: "Greetings!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Matt Minhyuk Joo

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/mattjoo/
  - title: instagram
    url: https://www.instagram.com/matt.joo/
  - title: youtube
    url: https://www.youtube.com/channel/UCNWrMv4BIN1N9uVm-VIUlxA
    
# Build settings
markdown: kramdown
permalink: pretty
